[tool.poetry]
name = "zhou-reddit"
version = "0.1.0"
description = ""
authors = ["jbfink <john.fink@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
praw = "^7.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
